-- CLYMAPPO.stg_dtn_dwo_ccb_cs_subr_pcn definition

CREATE TABLE CLYMAPPO.stg_dtn_dwo_ccb_cs_subr_pcn
(
    file_id int NOT NULL,
    file_name varchar(400) NOT NULL,
    cust_numb int NOT NULL,
    subr_numb varchar(20) NOT NULL,
    blpd_code varchar(8) NOT NULL,
    subr_type varchar(4),
    telp_type varchar(4) NOT NULL,
    titl varchar(160),
    frst_name varchar(320),
    last_name varchar(320),
    subr_stts varchar(4) NOT NULL,
    frst_pkgp_code varchar(32),
    pkgp_strt_date date,
    new_ppty_code varchar(12),
    dpst_txtp_code varchar(16),
    conx_txtp_code varchar(16),
    telp_allc_type varchar(4),
    hrdw_numb varchar(80),
    card_numb varchar(76) NOT NULL,
    sms_lang varchar(4),
    deal_numb varchar(32) NOT NULL,
    slmn_code varchar(20),
    agmt_chck_flag varchar(4),
    agmt_chck_date date,
    swon_dttm timestamp,
    swon_by varchar(48) NOT NULL,
    swon_resn_code varchar(32) NOT NULL,
    swon_area_code varchar(4),
    swof_dttm timestamp,
    swof_by varchar(48),
    swof_resn_code varchar(32),
    rcnx_resn_code varchar(32),
    leas_code varchar(20),
    leas_strt_date date,
    leas_expr_date date,
    leas_acex_date date,
    pswd_flag varchar(4),
    pswd varchar(16),
    memb_id varchar(80),
    remk varchar(2000),
    rcnx_paid_flag varchar(4),
    stop_bill_flag varchar(4),
    rfnd_dttm timestamp,
    old_cust_numb int,
    old_subr_numb varchar(20),
    new_cust_numb int,
    new_subr_numb varchar(20),
    last_chng_dttm timestamp,
    last_chng_by varchar(48) NOT NULL,
    id_type varchar(8),
    id_numb varchar(20),
    gndr varchar(4),
    occp_code varchar(12),
    marl_stts varchar(4),
    salr_levl varchar(4),
    educ_levl int,
    emal_addr varchar(40),
    ivr_lang varchar(4),
    ussd_lang varchar(4),
    from_optr_code varchar(20),
    mnpi_stts varchar(4),
    mnpo_stts varchar(4),
    chwr_cont_aou varchar(4) NOT NULL,
    cc_lang varchar(8),
    sbscrpn_id int NOT NULL,
    file_date date NOT NULL,
    execution_id int,
    load_date timestamp,
    load_user varchar(80) NOT NULL,
    process_name varchar(600) NOT NULL
)
PARTITION BY (stg_dtn_dwo_ccb_cs_subr_pcn.file_date);


CREATE PROJECTION CLYMAPPO.stg_dtn_dwo_ccb_cs_subr_pcn_super /*+basename(stg_dtn_dwo_ccb_cs_subr_pcn),createtype(L)*/ 
(
 file_id,
 file_name,
 cust_numb,
 subr_numb,
 blpd_code,
 subr_type,
 telp_type,
 titl,
 frst_name,
 last_name,
 subr_stts,
 frst_pkgp_code,
 pkgp_strt_date,
 new_ppty_code,
 dpst_txtp_code,
 conx_txtp_code,
 telp_allc_type,
 hrdw_numb,
 card_numb,
 sms_lang,
 deal_numb,
 slmn_code,
 agmt_chck_flag,
 agmt_chck_date,
 swon_dttm,
 swon_by,
 swon_resn_code,
 swon_area_code,
 swof_dttm,
 swof_by,
 swof_resn_code,
 rcnx_resn_code,
 leas_code,
 leas_strt_date,
 leas_expr_date,
 leas_acex_date,
 pswd_flag,
 pswd,
 memb_id,
 remk,
 rcnx_paid_flag,
 stop_bill_flag,
 rfnd_dttm,
 old_cust_numb,
 old_subr_numb,
 new_cust_numb,
 new_subr_numb,
 last_chng_dttm,
 last_chng_by,
 id_type,
 id_numb,
 gndr,
 occp_code,
 marl_stts,
 salr_levl,
 educ_levl,
 emal_addr,
 ivr_lang,
 ussd_lang,
 from_optr_code,
 mnpi_stts,
 mnpo_stts,
 chwr_cont_aou,
 cc_lang,
 sbscrpn_id,
 file_date,
 execution_id,
 load_date,
 load_user,
 process_name
)
AS
 SELECT stg_dtn_dwo_ccb_cs_subr_pcn.file_id,
        stg_dtn_dwo_ccb_cs_subr_pcn.file_name,
        stg_dtn_dwo_ccb_cs_subr_pcn.cust_numb,
        stg_dtn_dwo_ccb_cs_subr_pcn.subr_numb,
        stg_dtn_dwo_ccb_cs_subr_pcn.blpd_code,
        stg_dtn_dwo_ccb_cs_subr_pcn.subr_type,
        stg_dtn_dwo_ccb_cs_subr_pcn.telp_type,
        stg_dtn_dwo_ccb_cs_subr_pcn.titl,
        stg_dtn_dwo_ccb_cs_subr_pcn.frst_name,
        stg_dtn_dwo_ccb_cs_subr_pcn.last_name,
        stg_dtn_dwo_ccb_cs_subr_pcn.subr_stts,
        stg_dtn_dwo_ccb_cs_subr_pcn.frst_pkgp_code,
        stg_dtn_dwo_ccb_cs_subr_pcn.pkgp_strt_date,
        stg_dtn_dwo_ccb_cs_subr_pcn.new_ppty_code,
        stg_dtn_dwo_ccb_cs_subr_pcn.dpst_txtp_code,
        stg_dtn_dwo_ccb_cs_subr_pcn.conx_txtp_code,
        stg_dtn_dwo_ccb_cs_subr_pcn.telp_allc_type,
        stg_dtn_dwo_ccb_cs_subr_pcn.hrdw_numb,
        stg_dtn_dwo_ccb_cs_subr_pcn.card_numb,
        stg_dtn_dwo_ccb_cs_subr_pcn.sms_lang,
        stg_dtn_dwo_ccb_cs_subr_pcn.deal_numb,
        stg_dtn_dwo_ccb_cs_subr_pcn.slmn_code,
        stg_dtn_dwo_ccb_cs_subr_pcn.agmt_chck_flag,
        stg_dtn_dwo_ccb_cs_subr_pcn.agmt_chck_date,
        stg_dtn_dwo_ccb_cs_subr_pcn.swon_dttm,
        stg_dtn_dwo_ccb_cs_subr_pcn.swon_by,
        stg_dtn_dwo_ccb_cs_subr_pcn.swon_resn_code,
        stg_dtn_dwo_ccb_cs_subr_pcn.swon_area_code,
        stg_dtn_dwo_ccb_cs_subr_pcn.swof_dttm,
        stg_dtn_dwo_ccb_cs_subr_pcn.swof_by,
        stg_dtn_dwo_ccb_cs_subr_pcn.swof_resn_code,
        stg_dtn_dwo_ccb_cs_subr_pcn.rcnx_resn_code,
        stg_dtn_dwo_ccb_cs_subr_pcn.leas_code,
        stg_dtn_dwo_ccb_cs_subr_pcn.leas_strt_date,
        stg_dtn_dwo_ccb_cs_subr_pcn.leas_expr_date,
        stg_dtn_dwo_ccb_cs_subr_pcn.leas_acex_date,
        stg_dtn_dwo_ccb_cs_subr_pcn.pswd_flag,
        stg_dtn_dwo_ccb_cs_subr_pcn.pswd,
        stg_dtn_dwo_ccb_cs_subr_pcn.memb_id,
        stg_dtn_dwo_ccb_cs_subr_pcn.remk,
        stg_dtn_dwo_ccb_cs_subr_pcn.rcnx_paid_flag,
        stg_dtn_dwo_ccb_cs_subr_pcn.stop_bill_flag,
        stg_dtn_dwo_ccb_cs_subr_pcn.rfnd_dttm,
        stg_dtn_dwo_ccb_cs_subr_pcn.old_cust_numb,
        stg_dtn_dwo_ccb_cs_subr_pcn.old_subr_numb,
        stg_dtn_dwo_ccb_cs_subr_pcn.new_cust_numb,
        stg_dtn_dwo_ccb_cs_subr_pcn.new_subr_numb,
        stg_dtn_dwo_ccb_cs_subr_pcn.last_chng_dttm,
        stg_dtn_dwo_ccb_cs_subr_pcn.last_chng_by,
        stg_dtn_dwo_ccb_cs_subr_pcn.id_type,
        stg_dtn_dwo_ccb_cs_subr_pcn.id_numb,
        stg_dtn_dwo_ccb_cs_subr_pcn.gndr,
        stg_dtn_dwo_ccb_cs_subr_pcn.occp_code,
        stg_dtn_dwo_ccb_cs_subr_pcn.marl_stts,
        stg_dtn_dwo_ccb_cs_subr_pcn.salr_levl,
        stg_dtn_dwo_ccb_cs_subr_pcn.educ_levl,
        stg_dtn_dwo_ccb_cs_subr_pcn.emal_addr,
        stg_dtn_dwo_ccb_cs_subr_pcn.ivr_lang,
        stg_dtn_dwo_ccb_cs_subr_pcn.ussd_lang,
        stg_dtn_dwo_ccb_cs_subr_pcn.from_optr_code,
        stg_dtn_dwo_ccb_cs_subr_pcn.mnpi_stts,
        stg_dtn_dwo_ccb_cs_subr_pcn.mnpo_stts,
        stg_dtn_dwo_ccb_cs_subr_pcn.chwr_cont_aou,
        stg_dtn_dwo_ccb_cs_subr_pcn.cc_lang,
        stg_dtn_dwo_ccb_cs_subr_pcn.sbscrpn_id,
        stg_dtn_dwo_ccb_cs_subr_pcn.file_date,
        stg_dtn_dwo_ccb_cs_subr_pcn.execution_id,
        stg_dtn_dwo_ccb_cs_subr_pcn.load_date,
        stg_dtn_dwo_ccb_cs_subr_pcn.load_user,
        stg_dtn_dwo_ccb_cs_subr_pcn.process_name
 FROM CLYMAPPO.stg_dtn_dwo_ccb_cs_subr_pcn
 ORDER BY stg_dtn_dwo_ccb_cs_subr_pcn.file_id,
          stg_dtn_dwo_ccb_cs_subr_pcn.file_name,
          stg_dtn_dwo_ccb_cs_subr_pcn.cust_numb,
          stg_dtn_dwo_ccb_cs_subr_pcn.subr_numb,
          stg_dtn_dwo_ccb_cs_subr_pcn.blpd_code,
          stg_dtn_dwo_ccb_cs_subr_pcn.subr_type,
          stg_dtn_dwo_ccb_cs_subr_pcn.telp_type,
          stg_dtn_dwo_ccb_cs_subr_pcn.titl
SEGMENTED BY hash(stg_dtn_dwo_ccb_cs_subr_pcn.file_id, stg_dtn_dwo_ccb_cs_subr_pcn.cust_numb, stg_dtn_dwo_ccb_cs_subr_pcn.blpd_code, stg_dtn_dwo_ccb_cs_subr_pcn.subr_type, stg_dtn_dwo_ccb_cs_subr_pcn.telp_type, stg_dtn_dwo_ccb_cs_subr_pcn.subr_stts, stg_dtn_dwo_ccb_cs_subr_pcn.pkgp_strt_date, stg_dtn_dwo_ccb_cs_subr_pcn.telp_allc_type) ALL NODES;


SELECT MARK_DESIGN_KSAFE(1);





-- CLYMAPPO.stg_dtn_dwo_ccb_cs_cust definition

CREATE TABLE CLYMAPPO.stg_dtn_dwo_ccb_cs_cust
(
    file_id int NOT NULL,
    file_name varchar(600) NOT NULL,
    cust_numb int NOT NULL,
    blpd_code varchar(8) NOT NULL,
    cust_stts varchar(4) NOT NULL,
    titl varchar(160),
    frst_name varchar(500) NOT NULL,
    last_name varchar(500),
    id_type varchar(8) NOT NULL,
    id_numb varchar(20) NOT NULL,
    gndr varchar(4),
    date_of_brth date,
    occp_code varchar(12),
    ntnt_code varchar(16),
    marl_stts varchar(4),
    chld int,
    faml_memb int,
    salr_levl varchar(4),
    incl_dict varchar(4),
    good_stts varchar(4),
    lang varchar(4),
    grup_head varchar(4),
    leaf_cust varchar(4),
    pret_cust_numb int,
    grup_code int NOT NULL,
    grup_levl int NOT NULL,
    empl_flag varchar(4),
    rprt_levl_flag varchar(4) NOT NULL,
    pmnt_levl_flag varchar(4) NOT NULL,
    grup_subr_indc varchar(4) NOT NULL,
    home_telp_numb varchar(100),
    home_fax_numb varchar(100),
    offc_telp_numb varchar(100),
    offc_fax_numb varchar(100),
    emal_addr varchar(40),
    docm_addr_type varchar(8) NOT NULL,
    crtd_dttm timestamp,
    crtd_by varchar(48) NOT NULL,
    last_chng_dttm timestamp,
    last_chng_by varchar(48) NOT NULL,
    comp_code varchar(8),
    py_telp_numb varchar(21),
    file_date date NOT NULL,
    execution_id int,
    load_date timestamp,
    load_user varchar(80) NOT NULL,
    process_name varchar(600) NOT NULL
)
PARTITION BY (stg_dtn_dwo_ccb_cs_cust.file_date);


CREATE PROJECTION CLYMAPPO.stg_dtn_dwo_ccb_cs_cust_super /*+basename(stg_dtn_dwo_ccb_cs_cust),createtype(L)*/ 
(
 file_id,
 file_name,
 cust_numb,
 blpd_code,
 cust_stts,
 titl,
 frst_name,
 last_name,
 id_type,
 id_numb,
 gndr,
 date_of_brth,
 occp_code,
 ntnt_code,
 marl_stts,
 chld,
 faml_memb,
 salr_levl,
 incl_dict,
 good_stts,
 lang,
 grup_head,
 leaf_cust,
 pret_cust_numb,
 grup_code,
 grup_levl,
 empl_flag,
 rprt_levl_flag,
 pmnt_levl_flag,
 grup_subr_indc,
 home_telp_numb,
 home_fax_numb,
 offc_telp_numb,
 offc_fax_numb,
 emal_addr,
 docm_addr_type,
 crtd_dttm,
 crtd_by,
 last_chng_dttm,
 last_chng_by,
 comp_code,
 py_telp_numb,
 file_date,
 execution_id,
 load_date,
 load_user,
 process_name
)
AS
 SELECT stg_dtn_dwo_ccb_cs_cust.file_id,
        stg_dtn_dwo_ccb_cs_cust.file_name,
        stg_dtn_dwo_ccb_cs_cust.cust_numb,
        stg_dtn_dwo_ccb_cs_cust.blpd_code,
        stg_dtn_dwo_ccb_cs_cust.cust_stts,
        stg_dtn_dwo_ccb_cs_cust.titl,
        stg_dtn_dwo_ccb_cs_cust.frst_name,
        stg_dtn_dwo_ccb_cs_cust.last_name,
        stg_dtn_dwo_ccb_cs_cust.id_type,
        stg_dtn_dwo_ccb_cs_cust.id_numb,
        stg_dtn_dwo_ccb_cs_cust.gndr,
        stg_dtn_dwo_ccb_cs_cust.date_of_brth,
        stg_dtn_dwo_ccb_cs_cust.occp_code,
        stg_dtn_dwo_ccb_cs_cust.ntnt_code,
        stg_dtn_dwo_ccb_cs_cust.marl_stts,
        stg_dtn_dwo_ccb_cs_cust.chld,
        stg_dtn_dwo_ccb_cs_cust.faml_memb,
        stg_dtn_dwo_ccb_cs_cust.salr_levl,
        stg_dtn_dwo_ccb_cs_cust.incl_dict,
        stg_dtn_dwo_ccb_cs_cust.good_stts,
        stg_dtn_dwo_ccb_cs_cust.lang,
        stg_dtn_dwo_ccb_cs_cust.grup_head,
        stg_dtn_dwo_ccb_cs_cust.leaf_cust,
        stg_dtn_dwo_ccb_cs_cust.pret_cust_numb,
        stg_dtn_dwo_ccb_cs_cust.grup_code,
        stg_dtn_dwo_ccb_cs_cust.grup_levl,
        stg_dtn_dwo_ccb_cs_cust.empl_flag,
        stg_dtn_dwo_ccb_cs_cust.rprt_levl_flag,
        stg_dtn_dwo_ccb_cs_cust.pmnt_levl_flag,
        stg_dtn_dwo_ccb_cs_cust.grup_subr_indc,
        stg_dtn_dwo_ccb_cs_cust.home_telp_numb,
        stg_dtn_dwo_ccb_cs_cust.home_fax_numb,
        stg_dtn_dwo_ccb_cs_cust.offc_telp_numb,
        stg_dtn_dwo_ccb_cs_cust.offc_fax_numb,
        stg_dtn_dwo_ccb_cs_cust.emal_addr,
        stg_dtn_dwo_ccb_cs_cust.docm_addr_type,
        stg_dtn_dwo_ccb_cs_cust.crtd_dttm,
        stg_dtn_dwo_ccb_cs_cust.crtd_by,
        stg_dtn_dwo_ccb_cs_cust.last_chng_dttm,
        stg_dtn_dwo_ccb_cs_cust.last_chng_by,
        stg_dtn_dwo_ccb_cs_cust.comp_code,
        stg_dtn_dwo_ccb_cs_cust.py_telp_numb,
        stg_dtn_dwo_ccb_cs_cust.file_date,
        stg_dtn_dwo_ccb_cs_cust.execution_id,
        stg_dtn_dwo_ccb_cs_cust.load_date,
        stg_dtn_dwo_ccb_cs_cust.load_user,
        stg_dtn_dwo_ccb_cs_cust.process_name
 FROM CLYMAPPO.stg_dtn_dwo_ccb_cs_cust
 ORDER BY stg_dtn_dwo_ccb_cs_cust.file_id,
          stg_dtn_dwo_ccb_cs_cust.file_name,
          stg_dtn_dwo_ccb_cs_cust.cust_numb,
          stg_dtn_dwo_ccb_cs_cust.blpd_code,
          stg_dtn_dwo_ccb_cs_cust.cust_stts,
          stg_dtn_dwo_ccb_cs_cust.titl,
          stg_dtn_dwo_ccb_cs_cust.frst_name,
          stg_dtn_dwo_ccb_cs_cust.last_name
SEGMENTED BY hash(stg_dtn_dwo_ccb_cs_cust.file_id, stg_dtn_dwo_ccb_cs_cust.cust_numb, stg_dtn_dwo_ccb_cs_cust.blpd_code, stg_dtn_dwo_ccb_cs_cust.cust_stts, stg_dtn_dwo_ccb_cs_cust.id_type, stg_dtn_dwo_ccb_cs_cust.gndr, stg_dtn_dwo_ccb_cs_cust.date_of_brth, stg_dtn_dwo_ccb_cs_cust.marl_stts) ALL NODES;


SELECT MARK_DESIGN_KSAFE(1);



-- CLYMAPPO.stg_dtn_dwo_cbs_ar_invoice definition

CREATE TABLE CLYMAPPO.stg_dtn_dwo_cbs_ar_invoice
(
    file_id int NOT NULL,
    file_name varchar(600) NOT NULL,
    invoice_id numeric(22,2) NOT NULL,
    invoice_no varchar(336),
    parent_invoice_id numeric(22,2),
    trans_type varchar(112) NOT NULL,
    channel_id varchar(176),
    acct_id numeric(22,2) NOT NULL,
    pri_identity varchar(84),
    invoice_amt numeric(22,2) NOT NULL,
    open_amt numeric(22,2) NOT NULL,
    invoice_date timestamp,
    due_date date,
    invoice_status varchar(84) NOT NULL,
    bill_cycle_id varchar(120),
    trans_id numeric(22,2),
    tax_amt numeric(22,2),
    dispute_amt numeric(22,2),
    dispute_tax_amt numeric(22,2),
    pending_cr_amt numeric(22,2),
    aod_status varchar(84),
    close_date timestamp,
    reason_code varchar(144),
    remark varchar(592),
    oper_id varchar(336) NOT NULL,
    dept_id varchar(336) NOT NULL,
    last_update_date timestamp,
    entry_date timestamp,
    open_tax_amt numeric(22,2),
    invoice_type varchar(112) NOT NULL,
    ext_property varchar(16080),
    whtinvoiceflag varchar(1),
    file_date date NOT NULL,
    execution_id int,
    load_date timestamp,
    load_user varchar(80) NOT NULL,
    comp_cd varchar(20) NOT NULL,
    process_name varchar(600) NOT NULL
)
PARTITION BY (stg_dtn_dwo_cbs_ar_invoice.file_date);


CREATE PROJECTION CLYMAPPO.stg_dtn_dwo_cbs_ar_invoice_super /*+basename(stg_dtn_dwo_cbs_ar_invoice),createtype(L)*/ 
(
 file_id,
 file_name,
 invoice_id,
 invoice_no,
 parent_invoice_id,
 trans_type,
 channel_id,
 acct_id,
 pri_identity,
 invoice_amt,
 open_amt,
 invoice_date,
 due_date,
 invoice_status,
 bill_cycle_id,
 trans_id,
 tax_amt,
 dispute_amt,
 dispute_tax_amt,
 pending_cr_amt,
 aod_status,
 close_date,
 reason_code,
 remark,
 oper_id,
 dept_id,
 last_update_date,
 entry_date,
 open_tax_amt,
 invoice_type,
 ext_property,
 whtinvoiceflag,
 file_date,
 execution_id,
 load_date,
 load_user,
 comp_cd,
 process_name
)
AS
 SELECT stg_dtn_dwo_cbs_ar_invoice.file_id,
        stg_dtn_dwo_cbs_ar_invoice.file_name,
        stg_dtn_dwo_cbs_ar_invoice.invoice_id,
        stg_dtn_dwo_cbs_ar_invoice.invoice_no,
        stg_dtn_dwo_cbs_ar_invoice.parent_invoice_id,
        stg_dtn_dwo_cbs_ar_invoice.trans_type,
        stg_dtn_dwo_cbs_ar_invoice.channel_id,
        stg_dtn_dwo_cbs_ar_invoice.acct_id,
        stg_dtn_dwo_cbs_ar_invoice.pri_identity,
        stg_dtn_dwo_cbs_ar_invoice.invoice_amt,
        stg_dtn_dwo_cbs_ar_invoice.open_amt,
        stg_dtn_dwo_cbs_ar_invoice.invoice_date,
        stg_dtn_dwo_cbs_ar_invoice.due_date,
        stg_dtn_dwo_cbs_ar_invoice.invoice_status,
        stg_dtn_dwo_cbs_ar_invoice.bill_cycle_id,
        stg_dtn_dwo_cbs_ar_invoice.trans_id,
        stg_dtn_dwo_cbs_ar_invoice.tax_amt,
        stg_dtn_dwo_cbs_ar_invoice.dispute_amt,
        stg_dtn_dwo_cbs_ar_invoice.dispute_tax_amt,
        stg_dtn_dwo_cbs_ar_invoice.pending_cr_amt,
        stg_dtn_dwo_cbs_ar_invoice.aod_status,
        stg_dtn_dwo_cbs_ar_invoice.close_date,
        stg_dtn_dwo_cbs_ar_invoice.reason_code,
        stg_dtn_dwo_cbs_ar_invoice.remark,
        stg_dtn_dwo_cbs_ar_invoice.oper_id,
        stg_dtn_dwo_cbs_ar_invoice.dept_id,
        stg_dtn_dwo_cbs_ar_invoice.last_update_date,
        stg_dtn_dwo_cbs_ar_invoice.entry_date,
        stg_dtn_dwo_cbs_ar_invoice.open_tax_amt,
        stg_dtn_dwo_cbs_ar_invoice.invoice_type,
        stg_dtn_dwo_cbs_ar_invoice.ext_property,
        stg_dtn_dwo_cbs_ar_invoice.whtinvoiceflag,
        stg_dtn_dwo_cbs_ar_invoice.file_date,
        stg_dtn_dwo_cbs_ar_invoice.execution_id,
        stg_dtn_dwo_cbs_ar_invoice.load_date,
        stg_dtn_dwo_cbs_ar_invoice.load_user,
        stg_dtn_dwo_cbs_ar_invoice.comp_cd,
        stg_dtn_dwo_cbs_ar_invoice.process_name
 FROM CLYMAPPO.stg_dtn_dwo_cbs_ar_invoice
 ORDER BY stg_dtn_dwo_cbs_ar_invoice.file_id,
          stg_dtn_dwo_cbs_ar_invoice.file_name,
          stg_dtn_dwo_cbs_ar_invoice.invoice_id,
          stg_dtn_dwo_cbs_ar_invoice.invoice_no,
          stg_dtn_dwo_cbs_ar_invoice.parent_invoice_id,
          stg_dtn_dwo_cbs_ar_invoice.trans_type,
          stg_dtn_dwo_cbs_ar_invoice.channel_id,
          stg_dtn_dwo_cbs_ar_invoice.acct_id
SEGMENTED BY hash(stg_dtn_dwo_cbs_ar_invoice.file_id, stg_dtn_dwo_cbs_ar_invoice.invoice_date, stg_dtn_dwo_cbs_ar_invoice.due_date, stg_dtn_dwo_cbs_ar_invoice.close_date, stg_dtn_dwo_cbs_ar_invoice.last_update_date, stg_dtn_dwo_cbs_ar_invoice.entry_date, stg_dtn_dwo_cbs_ar_invoice.whtinvoiceflag, stg_dtn_dwo_cbs_ar_invoice.file_date) ALL NODES;


SELECT MARK_DESIGN_KSAFE(1);



-- CLYMAPPO.stg_dtn_dwo_cbs_ar_account_balance definition

CREATE TABLE CLYMAPPO.stg_dtn_dwo_cbs_ar_account_balance
(
    file_id int NOT NULL,
    file_name varchar(600) NOT NULL,
    acct_id numeric(22,2),
    acct_code varchar(256),
    ar_balance numeric(22,2),
    open_amt numeric(22,2),
    unapplied_amt numeric(22,2),
    dispute_amt numeric(22,2),
    pending_cr_amt numeric(22,2),
    last_trx_date timestamp,
    balance_update_date timestamp,
    last_payment_date timestamp,
    file_date date NOT NULL,
    execution_id int NOT NULL,
    load_date timestamp,
    load_user varchar(80) NOT NULL,
    comp_cd varchar(20) NOT NULL,
    process_name varchar(600) NOT NULL
)
PARTITION BY (stg_dtn_dwo_cbs_ar_account_balance.file_date);


CREATE PROJECTION CLYMAPPO.stg_dtn_dwo_cbs_ar_account_balance_super /*+basename(stg_dtn_dwo_cbs_ar_account_balance),createtype(L)*/ 
(
 file_id,
 file_name,
 acct_id,
 acct_code,
 ar_balance,
 open_amt,
 unapplied_amt,
 dispute_amt,
 pending_cr_amt,
 last_trx_date,
 balance_update_date,
 last_payment_date,
 file_date,
 execution_id,
 load_date,
 load_user,
 comp_cd,
 process_name
)
AS
 SELECT stg_dtn_dwo_cbs_ar_account_balance.file_id,
        stg_dtn_dwo_cbs_ar_account_balance.file_name,
        stg_dtn_dwo_cbs_ar_account_balance.acct_id,
        stg_dtn_dwo_cbs_ar_account_balance.acct_code,
        stg_dtn_dwo_cbs_ar_account_balance.ar_balance,
        stg_dtn_dwo_cbs_ar_account_balance.open_amt,
        stg_dtn_dwo_cbs_ar_account_balance.unapplied_amt,
        stg_dtn_dwo_cbs_ar_account_balance.dispute_amt,
        stg_dtn_dwo_cbs_ar_account_balance.pending_cr_amt,
        stg_dtn_dwo_cbs_ar_account_balance.last_trx_date,
        stg_dtn_dwo_cbs_ar_account_balance.balance_update_date,
        stg_dtn_dwo_cbs_ar_account_balance.last_payment_date,
        stg_dtn_dwo_cbs_ar_account_balance.file_date,
        stg_dtn_dwo_cbs_ar_account_balance.execution_id,
        stg_dtn_dwo_cbs_ar_account_balance.load_date,
        stg_dtn_dwo_cbs_ar_account_balance.load_user,
        stg_dtn_dwo_cbs_ar_account_balance.comp_cd,
        stg_dtn_dwo_cbs_ar_account_balance.process_name
 FROM CLYMAPPO.stg_dtn_dwo_cbs_ar_account_balance
 ORDER BY stg_dtn_dwo_cbs_ar_account_balance.file_id,
          stg_dtn_dwo_cbs_ar_account_balance.file_name,
          stg_dtn_dwo_cbs_ar_account_balance.acct_id,
          stg_dtn_dwo_cbs_ar_account_balance.acct_code,
          stg_dtn_dwo_cbs_ar_account_balance.ar_balance,
          stg_dtn_dwo_cbs_ar_account_balance.open_amt,
          stg_dtn_dwo_cbs_ar_account_balance.unapplied_amt,
          stg_dtn_dwo_cbs_ar_account_balance.dispute_amt
SEGMENTED BY hash(stg_dtn_dwo_cbs_ar_account_balance.file_id, stg_dtn_dwo_cbs_ar_account_balance.last_trx_date, stg_dtn_dwo_cbs_ar_account_balance.balance_update_date, stg_dtn_dwo_cbs_ar_account_balance.last_payment_date, stg_dtn_dwo_cbs_ar_account_balance.file_date, stg_dtn_dwo_cbs_ar_account_balance.execution_id, stg_dtn_dwo_cbs_ar_account_balance.load_date, stg_dtn_dwo_cbs_ar_account_balance.acct_id) ALL NODES;


SELECT MARK_DESIGN_KSAFE(1);