
CREATE TABLE CLYMAPPO.stg_sgv_customers (
    grading_account_id VARCHAR(100),
    identifier_no VARCHAR(50),
    id_type VARCHAR(50),
    customer_no VARCHAR(100),
    company_name VARCHAR(100),
    customer_status VARCHAR(100),
    customer_type VARCHAR(50),
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    title VARCHAR(50),
    birth_date DATE,
    gender VARCHAR(20),
    street VARCHAR(200),
    house_number VARCHAR(50),
    moo VARCHAR(50),
    postal_code VARCHAR(10),
    city VARCHAR(100),
    district VARCHAR(100),
    sub_district VARCHAR(100),
    country VARCHAR(50),
    room_number VARCHAR(50),
    floor VARCHAR(50),
    building_mooban VARCHAR(100),
    soi VARCHAR(100),
    email_address VARCHAR(254),
    golden_id VARCHAR(50),
	phone_number_list VARCHAR(10000),
    emp_employee_id VARCHAR(50),
    emp_company_name VARCHAR(100),
    emp_position_code VARCHAR(50),
    emp_employee_flag CHAR(10),
    operator_name VARCHAR(10),
    transaction_date DATE,
    partition_date DATE NOT NULL,  
    partition_month VARCHAR(10),
    processed_date DATE
)
UNSEGMENTED ALL NODES
PARTITION BY partition_date;

CREATE PROJECTION CLYMAPPO.stg_sgv_customers_super
(
    grading_account_id,
    identifier_no,
    id_type,
    customer_no,
    company_name,
    customer_status,
    customer_type,
    first_name,
    last_name,
    title,
    birth_date,
    gender,
    street,
    house_number,
    moo,
    postal_code,
    city,
    district,
    sub_district,
    country,
    room_number,
    floor,
    building_mooban,
    soi,
    email_address,
    golden_id,
    phone_number_list,
    emp_employee_id,
    emp_company_name,
    emp_position_code,
    emp_employee_flag,
    operator_name,
    transaction_date,
    partition_date,  
    partition_month,
    processed_date
)
AS 
SELECT 
    grading_account_id,
    identifier_no,
    id_type,
    customer_no,
    company_name,
    customer_status,
    customer_type,
    first_name,
    last_name,
    title,
    birth_date,
    gender,
    street,
    house_number,
    moo,
    postal_code,
    city,
    district,
    sub_district,
    country,
    room_number,
    floor,
    building_mooban,
    soi,
    email_address,
    golden_id,
    phone_number_list,
    emp_employee_id,
    emp_company_name,
    emp_position_code,
    emp_employee_flag,
    operator_name,
    transaction_date,
    partition_date,  
    partition_month,
    processed_date
FROM CLYMAPPO.stg_sgv_customers
ORDER BY partition_date, grading_account_id, identifier_no, id_type
SEGMENTED BY HASH(
    partition_date,
    grading_account_id,
    golden_id,
    identifier_no,
    customer_no,
    id_type,
    operator_name,
    customer_type
) ALL NODES;
