CREATE TABLE CLYMAPPO.stg_true_customers (
    row_key VARCHAR(60),
    notification_id VARCHAR(60),
    event_begin_time TIMESTAMP,
    id_num VARCHAR(50),
    id_type VARCHAR(50),
    company_name VARCHAR(100),
    customer_status VARCHAR(100),
    customer_type VARCHAR(50),
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    title VARCHAR(50),
    birth_date DATE,
    gender VARCHAR(20),
    street VARCHAR(200),
    house_number VARCHAR(50),
    moo VARCHAR(50),
    postal_code VARCHAR(10),
    city VARCHAR(100),
    district VARCHAR(100),
    sub_district VARCHAR(100),
    country VARCHAR(50),
    room_number VARCHAR(50),
    floor VARCHAR(50),
    building_mooban VARCHAR(100),
    soi VARCHAR(100),
    email_address VARCHAR(254),
    golden_id VARCHAR(50),
    phone_number_list VARCHAR(10000), 
    transaction_date DATE,
    partition_date DATE,  
    partition_month VARCHAR(10),
    processed_date DATE
)
UNSEGMENTED ALL NODES
PARTITION BY partition_date;


CREATE PROJECTION CLYMAPPO.stg_true_customers_super
(
    notification_id,
    event_begin_time,
    id_num,
    id_type,
    company_name,
    customer_status,
    customer_type,
    first_name,
    last_name,
    title,
    birth_date,
    gender,
    street,
    house_number,
    moo,
    postal_code,
    city,
    district,
    sub_district,
    country,
    room_number,
    floor,
    building_mooban,
    soi,
    email_address,
    golden_id,
    phone_number_list,
    transaction_date,
    partition_date,  
    partition_month,
    processed_date
)
AS 
SELECT 
    notification_id,
    event_begin_time,
    id_num,
    id_type,
    company_name,
    customer_status,
    customer_type,
    first_name,
    last_name,
    title,
    birth_date,
    gender,
    street,
    house_number,
    moo,
    postal_code,
    city,
    district,
    sub_district,
    country,
    room_number,
    floor,
    building_mooban,
    soi,
    email_address,
    golden_id,
    phone_number_list,
    transaction_date,
    partition_date,  
    partition_month,
    processed_date
FROM CLYMAPPO.stg_true_customers
ORDER BY partition_date, id_num, id_type
SEGMENTED BY HASH(
    partition_date,
    golden_id,
    id_num,
    id_type,
    notification_id,
    customer_type
) ALL NODES;
