CREATE TABLE CLYMAPPO.sgv_subscribers (
    grading_account_id VARCHAR(100),
    identifier_no VARCHAR(100),
    id_type VARCHAR(100),
    customer_type VARCHAR(100),
    customer_no VARCHAR(100),
    crm_integration_id VARCHAR(100),
    golden_id VARCHAR(100),
    product_id VARCHAR(100),
    product_name VARCHAR(200),
    product_name_desc VARCHAR(500),
    product_status VARCHAR(50),
    product_line VARCHAR(100),
    product_group VARCHAR(50),
    ban VARCHAR(100),
    billing_sub_no VARCHAR(100),
    start_date TIMESTAMP,
    end_date TIMESTAMP,
    language VARCHAR(20),
    street VARCHAR(200),
    house_number VARCHAR(200),
    moo VARCHAR(200),
    postal_code VARCHAR(200),
    city VARCHAR(200),
    district VARCHAR(200),
    sub_district VARCHAR(200),
    country VARCHAR(200),
    first_name VARCHAR(200),
    last_name VARCHAR(200),
    ou_id VARCHAR(100),
    vip VARCHAR(100),
    company_code VARCHAR(50),
    subscriber_code VARCHAR(255),
    subscriber_description VARCHAR(255),
    subscriber_type VARCHAR(100),
    subscriber_price_plan_code VARCHAR(255),
    subscriber_status VARCHAR(50),
    subscriber_start_date DATE,
    subscriber_end_date DATE,
    operator_name VARCHAR(50),
    create_at TIMESTAMP DEFAULT NOW(),
    update_at TIMESTAMP DEFAULT NOW(),
    transaction_date DATE,
    partition_date DATE NOT NULL,
    partition_month VARCHAR(10),
    processed_date DATE
)
UNSEGMENTED ALL NODES
PARTITION BY partition_date;

CREATE PROJECTION CLYMAPPO.sgv_subscribers_super
(
    grading_account_id,
    identifier_no,
    id_type,
    customer_type,
    customer_no,
    crm_integration_id,
    golden_id,
    product_id,
    product_name,
    product_name_desc,
    product_status,
    product_line,
    product_group,
    ban,
    billing_sub_no,
    start_date,
    end_date,
    language,
    street,
    house_number,
    moo,
    postal_code,
    city,
    district,
    sub_district,
    country,
    first_name,
    last_name,
    ou_id,
    vip,
    company_code,
    subscriber_code,
    subscriber_description,
    subscriber_type,
    subscriber_price_plan_code,
    subscriber_status,
    subscriber_start_date,
    subscriber_end_date,
    operator_name,
    create_at,
    update_at,
    transaction_date,
    partition_date,
    partition_month,
    processed_date
)
AS 
SELECT * FROM CLYMAPPO.sgv_subscribers
ORDER BY partition_date, identifier_no, product_id
SEGMENTED BY HASH(
    partition_date,
    grading_account_id,
    identifier_no,
    product_id,
    customer_no,
    crm_integration_id,
    golden_id,
    product_status,
    id_type,
    customer_type,
    ban,
    operator_name,
    vip,
    create_at,
    update_at
) ALL NODES;


CREATE TABLE CLYMAPPO.sgv_subscribers_history (
    grading_account_id VARCHAR(100),
    identifier_no VARCHAR(50),
    id_type VARCHAR(50),
    customer_type VARCHAR(50),
    customer_no VARCHAR(100),
    crm_integration_id VARCHAR(100),
    golden_id VARCHAR(50),
    product_id VARCHAR(100),
    product_name VARCHAR(200),
    product_name_desc VARCHAR(500),
    product_status VARCHAR(50),
    product_line VARCHAR(100),
    product_group VARCHAR(50),
    ban VARCHAR(50),
    billing_sub_no VARCHAR(50),
    start_date TIMESTAMP,
    end_date TIMESTAMP,
    language VARCHAR(20),
    street VARCHAR(200),
    house_number VARCHAR(50),
    moo VARCHAR(50),
    postal_code VARCHAR(10),
    city VARCHAR(100),
    district VARCHAR(100),
    sub_district VARCHAR(100),
    country VARCHAR(50),
    first_name VARCHAR(200),
    last_name VARCHAR(200),
    ou_id VARCHAR(50),
    vip VARCHAR(50),
    company_code VARCHAR(50),
    subscriber_code VARCHAR(255),
    subscriber_description VARCHAR(255),
    subscriber_type VARCHAR(100),
    subscriber_price_plan_code VARCHAR(255),
    subscriber_status VARCHAR(50),
    subscriber_start_date DATE,
    subscriber_end_date DATE,
    operator_name VARCHAR(50),
    create_at TIMESTAMP DEFAULT NOW(),
    update_at TIMESTAMP DEFAULT NOW(),
    transaction_date DATE,
    partition_date DATE NOT NULL,
    partition_month VARCHAR(10),
    processed_date DATE
)
UNSEGMENTED ALL NODES
PARTITION BY partition_date;

CREATE PROJECTION CLYMAPPO.sgv_subscribers_history_super
(
    grading_account_id,
    identifier_no,
    id_type,
    customer_type,
    customer_no,
    crm_integration_id,
    golden_id,
    product_id,
    product_name,
    product_name_desc,
    product_status,
    product_line,
    product_group,
    ban,
    billing_sub_no,
    start_date,
    end_date,
    language,
    street,
    house_number,
    moo,
    postal_code,
    city,
    district,
    sub_district,
    country,
    first_name,
    last_name,
    ou_id,
    vip,
    company_code,
    subscriber_code,
    subscriber_description,
    subscriber_type,
    subscriber_price_plan_code,
    subscriber_status,
    subscriber_start_date,
    subscriber_end_date,
    operator_name,
    create_at,
    update_at,
    transaction_date,
    partition_date,
    partition_month,
    processed_date
)
AS 
SELECT * FROM CLYMAPPO.sgv_subscribers_history
ORDER BY partition_date, identifier_no, product_id
SEGMENTED BY HASH(
    partition_date,
    grading_account_id,
    identifier_no,
    product_id,
    customer_no,
    crm_integration_id,
    golden_id,
    product_status,
    id_type,
    customer_type,
    ban,
    operator_name,
    vip,
    create_at,
    update_at
) ALL NODES;
