CREATE TABLE CLYMAPPO.stg_true_subscribers (
    row_key VARCHAR(60),
    notification_id VARCHAR(60),
    event_begin_time TIMESTAMP,
    id_num VARCHAR(100),
    id_type VARCHAR(100),
    customer_type VARCHAR(100),
    crm_integration_id VARCHAR(100),
    golden_id VARCHAR(100),
    product_id VARCHAR(100),
    product_name VARCHAR(200),
    product_name_desc VARCHAR(500),
    product_status VARCHAR(50),
    product_line VARCHAR(100),
    ban VARCHAR(100),
    billing_sub_no VARCHAR(100),
    start_date TIMESTAMP,
    end_date TIMESTAMP,
    language VARCHAR(20),
    street VARCHAR(200),
    house_number VARCHAR(200),
    moo VARCHAR(200),
    postal_code VARCHAR(200),
    city VARCHAR(200),
    district VARCHAR(200),
    sub_district VARCHAR(200),
    country VARCHAR(200),
    first_name VARCHAR(200),
    last_name VARCHAR(200),
    ou_id VARCHAR(100),
    vip VARCHAR(100),
    company_code VARCHAR(50),
    product_comp_list LONG VARCHAR(500000), 
    transaction_date DATE,
    partition_date DATE,  
    partition_month VARCHAR(10),
    processed_date DATE
)
UNSEGMENTED ALL NODES
PARTITION BY partition_date;

CREATE PROJECTION CLYMAPPO.stg_true_subscribers_super
(
    notification_id,
    event_begin_time,
    id_num,
    id_type,
    customer_type,
    crm_integration_id,
    golden_id,
    product_id,
    product_name,
    product_name_desc,
    product_status,
    product_line,
    ban,
    billing_sub_no,
    start_date,
    end_date,
    language,
    street,
    house_number,
    moo,
    postal_code,
    city,
    district,
    sub_district,
    country,
    first_name,
    last_name,
    ou_id,
    vip,
    company_code,
    product_comp_list,
    transaction_date,
    partition_date,  
    partition_month,
    processed_date
)
AS 
SELECT 
    notification_id,
    event_begin_time,
    id_num,
    id_type,
    customer_type,
    crm_integration_id,
    golden_id,
    product_id,
    product_name,
    product_name_desc,
    product_status,
    product_line,
    ban,
    billing_sub_no,
    start_date,
    end_date,
    language,
    street,
    house_number,
    moo,
    postal_code,
    city,
    district,
    sub_district,
    country,
    first_name,
    last_name,
    ou_id,
    vip,
    company_code,
    product_comp_list,
    transaction_date,
    partition_date,  
    partition_month,
    processed_date
FROM CLYMAPPO.stg_true_subscribers
ORDER BY partition_date, id_num, id_type
SEGMENTED BY HASH(
    partition_date,
    golden_id,
    id_num,
    id_type,
    notification_id,
    customer_type,
    ban,
    product_line,
    product_name
) ALL NODES;
