
CREATE TABLE CLYMAPPO.stg_sgv_subscribers
(
    grading_account_id varchar(100),
    identifier_no varchar(100),
    id_type varchar(100),
    customer_type varchar(100),
    customer_no varchar(100),
    crm_integration_id varchar(100),
    golden_id varchar(100),
    product_id varchar(100),
    product_name varchar(200),
    product_name_desc varchar(500),
    product_status varchar(50),
    product_line varchar(100),
    product_group varchar(50),
    ban varchar(100),
    billing_sub_no varchar(100),
    start_date timestamp,
    end_date timestamp,
    language varchar(20),
    street varchar(300),
    house_number varchar(300),
    moo varchar(300),
    postal_code varchar(300),
    city varchar(300),
    district varchar(300),
    sub_district varchar(300),
    country varchar(300),
    first_name varchar(300),
    last_name varchar(300),
    ou_id varchar(100),
    vip varchar(100),
    company_code varchar(50),
    subscriber_code varchar(255),
    subscriber_description varchar(255),
    subscriber_type varchar(100),
    subscriber_price_plan_code varchar(255),
    subscriber_status varchar(50),
    subscriber_start_date date,
    subscriber_end_date date,
    operator_name varchar(50),
    transaction_date date,
    partition_date date NOT NULL,
    partition_month varchar(10),
    processed_date date
)
UNSEGMENTED ALL NODES
PARTITION BY partition_date;
