CREATE TABLE CLYMAPPO.sgv_dtac_customers
(
    grading_account_id varchar(100),
    identifier_no varchar(50),
    id_type varchar(50),
    customer_no varchar(100),
    company_name varchar(100),
    customer_status varchar(100),
    customer_type varchar(50),
    first_name varchar(300),
    last_name varchar(300),
    title varchar(50),
    birth_date date,
    gender varchar(20),
    street varchar(200),
    house_number varchar(50),
    moo varchar(50),
    postal_code varchar(10),
    city varchar(100),
    district varchar(100),
    sub_district varchar(100),
    country varchar(50),
    room_number varchar(50),
    floor varchar(50),
    building_mooban varchar(100),
    soi varchar(100),
    email_address varchar(254),
    golden_id varchar(50),
    phone_number_list varchar(10000),
    emp_employee_id varchar(50),
    emp_company_name varchar(100),
    emp_position_code varchar(50),
    emp_employee_flag char(10),
    operator_name varchar(10),
    create_at timestamp DEFAULT now(),
    update_at timestamp DEFAULT now(),
    transaction_date date,
    partition_date date NOT NULL,
    partition_month varchar(10),
    processed_date date
)
PARTITION BY (partition_date);